### ISSUE TITLE
Bad plot parsing from the /reference page

### ISSUE THREAD

**Issue by Susexe** [cinemagoer/cinemagoerng#2]
Parsing a plot from the main page works fine. Sample movie: Kill Bill: Vol. 1.

#### Expected result
'After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her.'

#### Actual result
'After awakening from a four-year coma, a former assassin wreaks vengeance on the team of assassins who betrayed her.\n    \n        Awards:'

**Comment by uyar** [comment]
The reference page is a mess of a markup. But it's also the one that contains the most relevant data in one page. Maybe I'll switch to using other pages as the primary source.
